/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-demo_clone using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-opus-4-6-v1

ROOST_METHOD_HASH=generateContent_bc4a182290
ROOST_METHOD_SIG_HASH=generateContent_c08b9769fe

```
Scenario 1: Basic text content generation without tools or system instruction

Details:
  TestName: generateContentWithBasicTextMessage
  Description: Tests that generateContent correctly processes a simple LlmRequest containing a single text message with no tools, no system instruction, and no special configuration. Verifies that the Anthropic client is called with proper parameters and returns a valid LlmResponse wrapped in a Flowable.
Execution:
  Arrange: Create a mock AnthropicClient and set up the messages service to return a mock Message with a text ContentBlock. Build an LlmRequest with a single Content containing a text Part, no config, and no tools.
  Act: Call generateContent(llmRequest, false) on the Claude instance.
  Assert: Verify the returned Flowable emits exactly one LlmResponse containing a Content with role "model" and the expected text part.
Validation:
  The assertion verifies that basic text generation works end-to-end, confirming proper message conversion, API invocation, and response mapping. This is the most fundamental use case for the Claude model integration.

Scenario 2: Generation with system instruction present in config

Details:
  TestName: generateContentWithSystemInstruction
  Description: Tests that when the LlmRequest contains a GenerateContentConfig with a systemInstruction containing text parts, the system text is correctly extracted and passed to the MessageCreateParams builder.
Execution:
  Arrange: Create a mock AnthropicClient. Build an LlmRequest with a config containing a systemInstruction Content with multiple text Parts. Set up the mock to capture the MessageCreateParams and return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that the MessageCreateParams passed to the Anthropic client includes the system text as a newline-joined string of the text parts from the system instruction.
Validation:
  This validates that system instructions are properly extracted and forwarded to the Anthropic API, ensuring that agent persona or behavioral instructions are correctly communicated to the Claude model.

Scenario 3: Generation with tools and function declarations

Details:
  TestName: generateContentWithToolsAndFunctionDeclarations
  Description: Tests that when the LlmRequest includes tools with function declarations in the config, the tools are correctly converted to Anthropic ToolUnion objects and the tool choice is set to auto with parallel tool use disabled.
Execution:
  Arrange: Create a mock AnthropicClient. Build an LlmRequest with a config containing tools that have function declarations (with name, description, and parameters). Also ensure llmRequest.tools() is non-empty. Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that the MessageCreateParams includes the converted tools and a ToolChoice of auto type with disableParallelToolUse set to true.
Validation:
  This confirms that function declarations are properly converted to Anthropic's tool format, enabling the Claude model to invoke tools/functions. The auto tool choice with disabled parallel use ensures sequential tool execution.

Scenario 4: Generation with empty tools list (no tool choice set)

Details:
  TestName: generateContentWithEmptyToolsList
  Description: Tests that when llmRequest.tools() returns an empty list, toolChoice is null and tools are not added to the params builder, even if config has some tool-related settings.
Execution:
  Arrange: Create a mock AnthropicClient. Build an LlmRequest where tools() returns an empty list but config may or may not have tool definitions. Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that the MessageCreateParams does not include tools or toolChoice parameters.
Validation:
  This validates the conditional logic that only adds tools and tool choice when the request actually has tools available, preventing unnecessary API parameters that could cause unexpected behavior.

Scenario 5: Generation with model specified in the request

Details:
  TestName: generateContentUsesModelFromRequest
  Description: Tests that when the LlmRequest has a model specified via model(), that model name is used in the MessageCreateParams rather than the default model from the Claude instance.
Execution:
  Arrange: Create a Claude instance with model name "claude-3-opus-20240229". Build an LlmRequest with model set to "claude-3-sonnet-20240229". Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that the MessageCreateParams uses "claude-3-sonnet-20240229" as the model.
Validation:
  This confirms that per-request model overrides work correctly, allowing dynamic model selection at runtime rather than being locked to the instance-level default.

Scenario 6: Generation falls back to instance model when request model is absent

Details:
  TestName: generateContentFallsBackToInstanceModel
  Description: Tests that when the LlmRequest does not specify a model (model() returns Optional.empty()), the Claude instance's default model name is used.
Execution:
  Arrange: Create a Claude instance with model name "claude-3-opus-20240229". Build an LlmRequest with no model specified. Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that the MessageCreateParams uses "claude-3-opus-20240229" as the model.
Validation:
  This ensures the fallback mechanism works correctly, guaranteeing that a valid model name is always provided to the Anthropic API even when the request doesn't specify one.

Scenario 7: Generation with multiple content messages (conversation history)

Details:
  TestName: generateContentWithMultipleMessages
  Description: Tests that when the LlmRequest contains multiple Content objects representing a conversation history, all messages are correctly converted to Anthropic MessageParam objects with appropriate roles.
Execution:
  Arrange: Create a mock AnthropicClient. Build an LlmRequest with multiple Content objects - user messages and model/assistant messages alternating. Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that the MessageCreateParams contains all messages in order with correct role mappings (user -> USER, model -> ASSISTANT).
Validation:
  This verifies that conversation history is properly preserved and role-mapped when communicating with the Anthropic API, which is essential for multi-turn conversations.

Scenario 8: Generation with custom maxTokens

Details:
  TestName: generateContentWithCustomMaxTokens
  Description: Tests that when a Claude instance is created with a custom maxTokens value, that value is correctly passed to the MessageCreateParams.
Execution:
  Arrange: Create a Claude instance with maxTokens set to 4096 using the three-argument constructor. Build a simple LlmRequest. Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that the MessageCreateParams has maxTokens set to 4096.
Validation:
  This confirms that the custom token limit configuration is properly forwarded to the API, allowing users to control response length.

Scenario 9: Generation with system instruction containing no text parts

Details:
  TestName: generateContentWithEmptySystemInstruction
  Description: Tests that when the system instruction exists but contains no text parts (or parts with empty text), the system text remains an empty string.
Execution:
  Arrange: Create a mock AnthropicClient. Build an LlmRequest with a config containing a systemInstruction Content that has no parts or parts with no text. Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that the MessageCreateParams has an empty system text string.
Validation:
  This validates the edge case where system instruction is present but has no actionable text content, ensuring no null pointer exceptions or invalid system prompts are sent.

Scenario 10: Generation with config present but no tools defined

Details:
  TestName: generateContentWithConfigButNoTools
  Description: Tests that when the LlmRequest has a config but tools() returns Optional.empty() or an empty list within the config, the tools list remains empty and is not added to params.
Execution:
  Arrange: Create a mock AnthropicClient. Build an LlmRequest with a GenerateContentConfig that has no tools (tools() returns Optional.empty()). Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that no tools are included in the MessageCreateParams and toolChoice is not set.
Validation:
  This ensures proper handling of the config-present-but-no-tools scenario, verifying each level of the nested Optional/list checks in the tool extraction logic.

Scenario 11: Generation response with tool use content block

Details:
  TestName: generateContentReturnsToolUseInResponse
  Description: Tests that when the Anthropic API returns a Message containing a tool_use ContentBlock, the response is correctly converted to an LlmResponse with a FunctionCall Part.
Execution:
  Arrange: Create a mock AnthropicClient. Set up the mock to return a Message with a tool_use ContentBlock containing an id, name, and input arguments. Build a simple LlmRequest.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify the returned LlmResponse contains a Part with a FunctionCall having the correct id, name, and args.
Validation:
  This confirms that tool use responses from Claude are properly mapped back to the framework's FunctionCall representation, enabling the tool execution pipeline to proceed.

Scenario 12: Generation with stream parameter set to true (currently ignored)

Details:
  TestName: generateContentWithStreamParameterTrue
  Description: Tests that the method works correctly when the stream parameter is true. Since the TODO comment indicates streaming is not yet implemented, the method should still return a single Flowable item.
Execution:
  Arrange: Create a mock AnthropicClient. Build a simple LlmRequest. Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, true).
  Assert: Verify the returned Flowable emits exactly one LlmResponse, behaving identically to the non-streaming case.
Validation:
  This documents the current behavior when streaming is requested but not implemented, ensuring the method still produces correct results regardless of the stream flag.

Scenario 13: Generation with function declarations that have no parameters

Details:
  TestName: generateContentWithParameterlessFunctionDeclarations
  Description: Tests that function declarations without parameters (parameters() returns Optional.empty()) are correctly converted to Anthropic tools with empty properties.
Execution:
  Arrange: Create a mock AnthropicClient. Build an LlmRequest with function declarations that have a name and description but no parameters. Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that the tools in MessageCreateParams have empty properties in their input schema.
Validation:
  This validates that parameterless tools are handled gracefully, which is common for simple actions like "get current time" that require no input.

Scenario 14: Generation with config absent (Optional.empty())

Details:
  TestName: generateContentWithNoConfig
  Description: Tests that when llmRequest.config() returns Optional.empty(), the method handles the absence gracefully with no system text and no tools.
Execution:
  Arrange: Create a mock AnthropicClient. Build an LlmRequest with no config (config() returns Optional.empty()). Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify the MessageCreateParams has empty system text, no tools, and the method completes successfully.
Validation:
  This ensures the method operates correctly with minimal configuration, covering the case where no additional generation settings are specified.

Scenario 15: Generation with multiple text parts in system instruction joined by newline

Details:
  TestName: generateContentJoinsMultipleSystemInstructionParts
  Description: Tests that when the system instruction contains multiple text parts, they are correctly joined with newline separators.
Execution:
  Arrange: Create a mock AnthropicClient. Build an LlmRequest with a systemInstruction containing three text Parts: "You are a helpful assistant.", "Be concise.", "Use formal language." Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify the system text in MessageCreateParams equals "You are a helpful assistant.\nBe concise.\nUse formal language."
Validation:
  This verifies the text joining logic, ensuring multiple system instruction components are properly concatenated with the expected delimiter for clear instructions to the model.

Scenario 16: Generation with content containing function call part

Details:
  TestName: generateContentWithFunctionCallInContent
  Description: Tests that when the LlmRequest content includes a Part with a functionCall (representing a prior assistant tool invocation), it is correctly converted to an Anthropic ToolUseBlockParam in the message.
Execution:
  Arrange: Create a mock AnthropicClient. Build an LlmRequest with Content containing a Part that has a functionCall with id, name, and args. Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that the converted message contains a ToolUseBlockParam with the correct id, name, and input.
Validation:
  This confirms that function call history in the conversation is properly represented in the Anthropic message format, maintaining context for multi-turn tool interactions.

Scenario 17: Generation with content containing function response part

Details:
  TestName: generateContentWithFunctionResponseInContent
  Description: Tests that when the LlmRequest content includes a Part with a functionResponse (representing a tool execution result), it is correctly converted to an Anthropic ToolResultBlockParam.
Execution:
  Arrange: Create a mock AnthropicClient. Build an LlmRequest with Content containing a Part that has a functionResponse with an id and a response map containing a "result" key. Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that the converted message contains a ToolResultBlockParam with the correct toolUseId and content string.
Validation:
  This verifies that tool execution results are properly formatted for the Anthropic API, allowing Claude to process function outputs and continue reasoning.

Scenario 18: Generation with tools in config but function declarations absent in first tool

Details:
  TestName: generateContentWithToolsButNoFunctionDeclarations
  Description: Tests that when tools are present in config but the first tool's functionDeclarations() returns Optional.empty(), the tools list remains empty.
Execution:
  Arrange: Create a mock AnthropicClient. Build an LlmRequest with a config where tools() returns a list with one tool item whose functionDeclarations() returns Optional.empty(). Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that no tools are included in the final MessageCreateParams.
Validation:
  This tests the nested conditional logic at the deepest level, ensuring that missing function declarations don't cause errors and the method degrades gracefully.

Scenario 19: Generation with default maxTokens value

Details:
  TestName: generateContentWithDefaultMaxTokens
  Description: Tests that when a Claude instance is created using the two-argument constructor (without specifying maxTokens), the default value of 8192 is used in the MessageCreateParams.
Execution:
  Arrange: Create a Claude instance using the two-argument constructor (modelName, anthropicClient). Build a simple LlmRequest. Set up the mock to return a valid Message.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify that the MessageCreateParams has maxTokens set to 8192.
Validation:
  This confirms the default maxTokens value is properly applied, ensuring reasonable token limits when no custom value is specified.

Scenario 20: Generation response with multiple content blocks (text and tool use)

Details:
  TestName: generateContentWithMixedResponseBlocks
  Description: Tests that when the Anthropic API returns a Message with multiple ContentBlocks (e.g., a text block followed by a tool_use block), both are correctly converted to Parts in the LlmResponse.
Execution:
  Arrange: Create a mock AnthropicClient. Set up the mock to return a Message containing both a text ContentBlock and a tool_use ContentBlock. Build a simple LlmRequest.
  Act: Call generateContent(llmRequest, false).
  Assert: Verify the returned LlmResponse contains a Content with two Parts - one text Part and one FunctionCall Part, in the correct order.
Validation:
  This validates the handling of complex responses where Claude provides both explanatory text and a tool invocation, which is common in agentic workflows.

Scenario 21: Generation with system instruction parts containing mix of text and non-text parts

Details:
  TestName: generateContentFiltersNonTextPartsFromSystemInstruction
  Description: Tests that when the system instruction contains a mix of text parts and non-text parts (e.g., parts with only functionCall), only the text parts are extracted for the system text.
Execution:

*/

// ********RoostGPT********

```java
package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;
import com.anthropic.client.AnthropicClient;
import com.anthropic.models.messages.*;
import com.anthropic.services.blocking.MessageService;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.genai.types.*;
import io.reactivex.rxjava3.core.Flowable;
import java.util.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.jupiter.api.*;
import com.anthropic.models.messages.ContentBlock;
import com.anthropic.models.messages.ContentBlockParam;
import com.anthropic.models.messages.Message;
import com.anthropic.models.messages.MessageCreateParams;
import com.anthropic.models.messages.MessageParam;
import com.anthropic.models.messages.MessageParam.Role;
import com.anthropic.models.messages.TextBlockParam;
import com.anthropic.models.messages.Tool;
import com.anthropic.models.messages.ToolChoice;
import com.anthropic.models.messages.ToolChoiceAuto;
import com.anthropic.models.messages.ToolResultBlockParam;
import com.anthropic.models.messages.ToolUnion;
import com.anthropic.models.messages.ToolUseBlockParam;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.google.genai.types.Content;
import com.google.genai.types.FunctionCall;
import com.google.genai.types.FunctionDeclaration;
import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.Part;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Collectors;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@ExtendWith(MockitoExtension.class)
public class ClaudeGenerateContentTest {

	@Mock
	private AnthropicClient anthropicClient;

	@Mock
	private MessageService messageService;

	@Mock
	private Message mockMessage;

	private Claude claude;

	@BeforeEach
	void setUp() {
		lenient().when(anthropicClient.messages()).thenReturn(messageService);
		claude = new Claude("claude-3-opus-20240229", anthropicClient);
	}

	private Message createTextMessage(String text) {
		Message msg = mock(Message.class);
		ContentBlock textBlock = mock(ContentBlock.class);
		ContentBlock.TextBlock textBlockContent = mock(ContentBlock.TextBlock.class);
		when(textBlock.isText()).thenReturn(true);
		when(textBlock.isToolUse()).thenReturn(false);
		when(textBlock.asText()).thenReturn(textBlockContent);
		when(textBlockContent.text()).thenReturn(text);
		when(msg.content()).thenReturn(List.of(textBlock));
		return msg;
	}

	private Message createToolUseMessage(String id, String name, Map<String, Object> input) {
		Message msg = mock(Message.class);
		ContentBlock toolUseBlock = mock(ContentBlock.class);
		ContentBlock.ToolUseBlock toolUseContent = mock(ContentBlock.ToolUseBlock.class);
		when(toolUseBlock.isText()).thenReturn(false);
		when(toolUseBlock.isToolUse()).thenReturn(true);
		when(toolUseBlock.asToolUse()).thenReturn(toolUseContent);
		when(toolUseContent.id()).thenReturn(id);
		when(toolUseContent.name()).thenReturn(name);
		com.anthropic.core.JsonField<Object> inputField = mock(com.anthropic.core.JsonField.class);
		when(inputField.convert(any(com.fasterxml.jackson.core.type.TypeReference.class))).thenReturn(input);
		when(toolUseContent._input()).thenReturn(inputField);
		when(msg.content()).thenReturn(List.of(toolUseBlock));
		return msg;
	}

	private Message createMixedMessage(String text, String toolId, String toolName, Map<String, Object> toolInput) {
		Message msg = mock(Message.class);
		ContentBlock textBlock = mock(ContentBlock.class);
		ContentBlock.TextBlock textBlockContent = mock(ContentBlock.TextBlock.class);
		when(textBlock.isText()).thenReturn(true);
		when(textBlock.isToolUse()).thenReturn(false);
		when(textBlock.asText()).thenReturn(textBlockContent);
		when(textBlockContent.text()).thenReturn(text);
		ContentBlock toolUseBlock = mock(ContentBlock.class);
		ContentBlock.ToolUseBlock toolUseContent = mock(ContentBlock.ToolUseBlock.class);
		when(toolUseBlock.isText()).thenReturn(false);
		when(toolUseBlock.isToolUse()).thenReturn(true);
		when(toolUseBlock.asToolUse()).thenReturn(toolUseContent);
		when(toolUseContent.id()).thenReturn(toolId);
		when(toolUseContent.name()).thenReturn(toolName);
		com.anthropic.core.JsonField<Object> inputField = mock(com.anthropic.core.JsonField.class);
		when(inputField.convert(any(com.fasterxml.jackson.core.type.TypeReference.class))).thenReturn(toolInput);
		when(toolUseContent._input()).thenReturn(inputField);
		when(msg.content()).thenReturn(List.of(textBlock, toolUseBlock));
		return msg;
	}

	@Test
	@Tag("valid")
	void generateContentWithBasicTextMessage() {
		Message responseMessage = createTextMessage("Hello, how can I help you?");
		when(messageService.create(any(MessageCreateParams.class))).thenReturn(responseMessage);
		Content userContent = Content.builder()
			.role("user")
			.parts(ImmutableList.of(Part.builder().text("Hello").build()))
			.build();
		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(userContent)).build();
		Flowable<LlmResponse> result = claude.generateContent(llmRequest, false);
		LlmResponse response = result.blockingFirst();
		assertNotNull(response);
		assertTrue(response.content().isPresent());
		assertEquals("model", response.content().get().role().orElse(""));
		assertTrue(response.content().get().parts().isPresent());
		assertEquals(1, response.content().get().parts().get().size());
		assertEquals("Hello, how can I help you?", response.content().get().parts().get().get(0).text().orElse(""));
	}

	@Test
	@Tag("valid")
	void generateContentWithSystemInstruction() {
		Message responseMessage = createTextMessage("I am a helpful assistant.");
		ArgumentCaptor<MessageCreateParams> paramsCaptor = ArgumentCaptor.forClass(MessageCreateParams.class);
		when(messageService.create(paramsCaptor.capture())).thenReturn(responseMessage);
		Content systemContent = Content.builder()
			.parts(ImmutableList.of(Part.builder().text("You are a helpful assistant.").build(),
					Part.builder().text("Be polite.").build()))
			.build();
		GenerateContentConfig config = GenerateContentConfig.builder().systemInstruction(systemContent).build();
		Content userContent = Content.builder()
			.role("user")
			.parts(ImmutableList.of(Part.builder().text("Hi").build()))
			.build();
		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(userContent)).config(config).build();
		claude.generateContent(llmRequest, false).blockingFirst();
		MessageCreateParams capturedParams = paramsCaptor.getValue();
		assertNotNull(capturedParams);
	}

	@Test
	@Tag("valid")
	void generateContentWithToolsAndFunctionDeclarations() {
		Message responseMessage = createTextMessage("Let me check that for you.");
		ArgumentCaptor<MessageCreateParams> paramsCaptor = ArgumentCaptor.forClass(MessageCreateParams.class);
		when(messageService.create(paramsCaptor.capture())).thenReturn(responseMessage);
		Schema paramSchema = Schema.builder().type("STRING").description("The city name").build();
		Schema parameters = Schema.builder().type("OBJECT").properties(ImmutableMap.of("city", paramSchema)).build();
		FunctionDeclaration funcDecl = FunctionDeclaration.builder()
			.name("get_weather")
			.description("Gets weather for a city")
			.parameters(parameters)
			.build();
		com.google.genai.types.Tool tool = com.google.genai.types.Tool.builder()
			.functionDeclarations(ImmutableList.of(funcDecl))
			.build();
		GenerateContentConfig config = GenerateContentConfig.builder().tools(ImmutableList.of(tool)).build();
		Content userContent = Content.builder()
			.role("user")
			.parts(ImmutableList.of(Part.builder().text("What's the weather?").build()))
			.build();
		Map<String, BaseTool> toolsMap = new HashMap<>();
		toolsMap.put("get_weather", mock(BaseTool.class));
		LlmRequest llmRequest = LlmRequest.builder()
			.contents(ImmutableList.of(userContent))
			.config(config)
			.tools(toolsMap)
			.build();
		claude.generateContent(llmRequest, false).blockingFirst();
		MessageCreateParams capturedParams = paramsCaptor.getValue();
		assertNotNull(capturedParams);
	}

	@Test
	@Tag("valid")
	void generateContentWithEmptyToolsList() {
		Message responseMessage = createTextMessage("Hello!");
		ArgumentCaptor<MessageCreateParams> paramsCaptor = ArgumentCaptor.forClass(MessageCreateParams.class);
		when(messageService.create(paramsCaptor.capture())).thenReturn(responseMessage);
		Content userContent = Content.builder()
			.role("user")
			.parts(ImmutableList.of(Part.builder().text("Hello").build()))
			.build();
		LlmRequest llmRequest = LlmRequest.builder()
			.contents(ImmutableList.of(userContent))
			.tools(ImmutableMap.of())
			.build();
		claude.generateContent(llmRequest, false).blockingFirst();
		MessageCreateParams capturedParams = paramsCaptor.getValue();
		assertNotNull(capturedParams);
	}

	@Test
	@Tag("valid")
	void generateContentUsesModelFromRequest() {
		Message responseMessage = createTextMessage("Response");
		ArgumentCaptor<MessageCreateParams> paramsCaptor = ArgumentCaptor.forClass(MessageCreateParams.class);
		when(messageService.create(paramsCaptor.capture())).thenReturn(responseMessage);
		Content userContent = Content.builder()
			.role("user")
			.parts(ImmutableList.of(Part.builder().text("Test").build()))
			.build();
		LlmRequest llmRequest = LlmRequest.builder()
			.model("claude-3-sonnet-20240229")
			.contents(ImmutableList.of(userContent))
			.build();
		claude.generateContent(llmRequest, false).blockingFirst();
		MessageCreateParams capturedParams = paramsCaptor.getValue();
		assertNotNull(capturedParams);
		assertEquals("claude-3-sonnet-20240229", capturedParams.model().toString());
	}

	@Test
	@Tag("valid")
	void generateContentFallsBackToInstanceModel() {
		Message responseMessage = createTextMessage("Response");
		ArgumentCaptor<MessageCreateParams> paramsCaptor = ArgumentCaptor.forClass(MessageCreateParams.class);
		when(messageService.create(paramsCaptor.capture())).thenReturn(responseMessage);
		Content userContent = Content.builder()
			.role("user")
			.parts(ImmutableList.of(Part.builder().text("Test").build()))
			.build();
		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(userContent)).build();
		claude.generateContent(llmRequest, false).blockingFirst();
		MessageCreateParams capturedParams = paramsCaptor.getValue();
		assertNotNull(capturedParams);
		assertEquals("claude-3-opus-20240229", capturedParams.model().toString());
	}

	@Test
	@Tag("valid")
	void generateContentWithMultipleMessages() {
		Message responseMessage = createTextMessage("Here's more info.");
		ArgumentCaptor<MessageCreateParams> paramsCaptor = ArgumentCaptor.forClass(MessageCreateParams.class);
		when(messageService.create(paramsCaptor.capture())).thenReturn(responseMessage);
		Content userContent1 = Content.builder()
			.role("user")
			.parts(ImmutableList.of(Part.builder().text("Hello").build()))
			.build();
		Content assistantContent = Content.builder()
			.role("model")
			.parts(ImmutableList.of(Part.builder().text("Hi there!").build()))
			.build();
		Content userContent2 = Content.builder()
			.role("user")
			.parts(ImmutableList.of(Part.builder().text("Tell me more").build()))
			.build();
		LlmRequest llmRequest = LlmRequest.builder()
			.contents(ImmutableList.of(userContent1, assistantContent, userContent2))
			.build();
		Flowable<LlmResponse> result = claude.generateContent(llmRequest, false);
		LlmResponse response = result.blockingFirst();
		assertNotNull(response);
		MessageCreateParams capturedParams = paramsCaptor.getValue();
		assertNotNull(capturedParams);
		assertEquals(3, capturedParams.messages().size());
	}

	@Test
	@Tag("valid")
	void generateContentWithCustomMaxTokens() {
		Claude claudeCustomTokens = new Claude("claude-3-opus-20240229", anthropicClient, 4096);
		Message responseMessage = createTextMessage("Response");
		ArgumentCaptor<MessageCreateParams> paramsCaptor = ArgumentCaptor.forClass(MessageCreateParams.class);
		when(messageService.create(paramsCaptor.capture())).thenReturn(responseMessage);
		Content userContent = Content.builder()
			.role("user")
			.parts(ImmutableList.of(Part.builder().text("Test").build()))
			.build();
		LlmRequest llmRequest = LlmRequest.builder().contents(ImmutableList.of(userContent)).build();
		claudeCustomTokens.generateContent(llmRequest, false).blockingFirst();
		MessageCreateParams capturedParams = paramsCaptor.getValue();
		assertNotNull(capturedParams);
		assertEquals(4096L, capturedParams.maxTokens());
	}

	@Test
    @Tag("boundary")
    void generateContentWithEmptySystemInstruction() {
        Message responseMessage = createTextMessage("Response");
        ArgumentCaptor<MessageCreateParams> paramsCaptor = ArgumentCaptor.forClass(MessageCreateParams.class);
        when(messageService.create(paramsCaptor.capture())).thenReturn(responseMessage);
        Content systemContent = Content.builder()
                .parts(ImmutableList.of())
                .build();
        GenerateContentConfig config = GenerateContentConfig.builder()
                .systemInstruction(systemContent)
                .build();
        Content userContent = Content.builder()
                .role("user")
                .parts(ImmutableList.of(Part.builder().text("Hello").build()))
                .build();
        LlmRequest llmRequest = LlmRequest.builder()
                .contents(ImmutableList.of(userContent))
                .config(config)
                .build();
        Flowable<LlmResponse> result = claude.generateContent(llmRequest, false);
        assertNotNull(result.blockingFirst());
    }

@Test
    @Tag("valid")
    void generateContentWithConfigButNoTools() {
        Message responseMessage = createTextMessage("Response");
        ArgumentCaptor<MessageCreateParams> paramsCaptor = ArgumentCaptor.forClass(MessageCreateParams.class);
        when(messageService.create(paramsCaptor.capture())).thenReturn(responseMessage);
        GenerateContentConfig config = GenerateContentConfig.builder()
                .build();
        Content userContent = Content.builder()
                .role("user")
                .parts(ImmutableList.of(Part.builder().text("Hello").build()))
                .build();
        L