/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test adk-java-demo_clone using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-opus-4-6-v1

ROOST_METHOD_HASH=registerLlm_39033090dc
ROOST_METHOD_SIG_HASH=registerLlm_6d1828529e

Scenario 1: Register a new LLM factory with a unique model name pattern

Details:
  TestName: registerLlmWithNewUniquePattern
  Description: Verify that calling registerLlm with a new model name pattern that does not already exist in the registry successfully adds the factory to the llmFactories map, making it available for subsequent LLM lookups.
Execution:
  Arrange: Create a custom LlmFactory implementation (e.g., a mock or lambda) and define a unique model name pattern (e.g., "custom-model-.*") that is not already registered.
  Act: Call LlmRegistry.registerLlm("custom-model-.*", factory).
  Assert: Call LlmRegistry.getLlm("custom-model-test") and assert that the returned BaseLlm instance is the one created by the custom factory.
Validation:
  The assertion verifies that the factory was successfully registered and is used when a matching model name is requested. This confirms the basic functionality of registerLlm in adding new factory entries to the registry.

Scenario 2: Register an LLM factory that overwrites an existing pattern

Details:
  TestName: registerLlmOverwritesExistingPatternFactory
  Description: Verify that calling registerLlm with a model name pattern that already exists in the registry replaces the existing factory with the new one, since the underlying data structure is a ConcurrentHashMap which uses put semantics.
Execution:
  Arrange: Create two different LlmFactory implementations (factoryA and factoryB). Register factoryA with pattern "overwrite-.*" first.
  Act: Call LlmRegistry.registerLlm("overwrite-.*", factoryB) to overwrite the previously registered factory.
  Assert: Call LlmRegistry.getLlm("overwrite-test") and verify that the returned instance was created by factoryB, not factoryA.
Validation:
  The assertion confirms that the ConcurrentHashMap's put method replaces the old value for the same key. This is significant because it allows users to override default factory registrations with custom ones.

Scenario 3: Register an LLM factory with an empty string pattern

Details:
  TestName: registerLlmWithEmptyStringPattern
  Description: Verify that registerLlm accepts an empty string as a model name pattern. An empty regex pattern matches only empty strings, so this tests edge case behavior of the registry with unusual patterns.
Execution:
  Arrange: Create a custom LlmFactory implementation that returns a mock BaseLlm instance.
  Act: Call LlmRegistry.registerLlm("", factory).
  Assert: Call LlmRegistry.getLlm("") and verify that it returns the instance created by the factory. Also verify that calling getLlm with a non-empty string that doesn't match other patterns throws IllegalArgumentException.
Validation:
  The assertion verifies that even an empty string pattern can be registered and used for matching. This tests the boundary condition of the regex matching mechanism and confirms the registry handles unusual inputs gracefully.

Scenario 4: Register an LLM factory with a complex regex pattern

Details:
  TestName: registerLlmWithComplexRegexPattern
  Description: Verify that registerLlm correctly stores a complex regex pattern and that the pattern is properly used for matching during LLM instance creation.
Execution:
  Arrange: Create a custom LlmFactory. Define a complex regex pattern such as "my-org/[a-z]+-v[0-9]+\\..*".
  Act: Call LlmRegistry.registerLlm("my-org/[a-z]+-v[0-9]+\\..*", factory).
  Assert: Call LlmRegistry.getLlm("my-org/model-v1.0") and verify it returns the expected instance. Also call LlmRegistry.getLlm("my-org/MODEL-v1.0") and verify it throws IllegalArgumentException since uppercase letters don't match [a-z]+.
Validation:
  The assertion confirms that the regex pattern registered via registerLlm is used as-is for pattern matching. This is important for ensuring that users can leverage the full power of Java regex for model name matching.

Scenario 5: Register multiple LLM factories with different patterns

Details:
  TestName: registerMultipleLlmFactoriesWithDifferentPatterns
  Description: Verify that multiple factories can be registered with different model name patterns and that the correct factory is invoked based on the model name provided to getLlm.
Execution:
  Arrange: Create three different LlmFactory implementations (factoryA, factoryB, factoryC). Register them with patterns "alpha-.*", "beta-.*", and "gamma-.*" respectively.
  Act: Call LlmRegistry.getLlm("alpha-1"), LlmRegistry.getLlm("beta-2"), and LlmRegistry.getLlm("gamma-3").
  Assert: Verify that each returned BaseLlm instance was created by its corresponding factory.
Validation:
  The assertion verifies that the registry can hold multiple factory registrations simultaneously and route model name lookups to the correct factory. This confirms the core multi-factory capability of the registry.

Scenario 6: Register an LLM factory with a null factory reference

Details:
  TestName: registerLlmWithNullFactory
  Description: Verify the behavior of registerLlm when a null factory is passed. Since ConcurrentHashMap does not allow null values, this should throw a NullPointerException.
Execution:
  Arrange: Prepare a valid model name pattern string "null-test-.*".
  Act: Call LlmRegistry.registerLlm("null-test-.*", null).
  Assert: Verify that a NullPointerException is thrown.
Validation:
  The assertion confirms that the ConcurrentHashMap's contract (no null keys or values) is enforced. This is important for ensuring data integrity in the registry and providing clear error feedback to developers who accidentally pass null.

Scenario 7: Register an LLM factory with a null model name pattern

Details:
  TestName: registerLlmWithNullModelNamePattern
  Description: Verify the behavior of registerLlm when a null model name pattern is passed. Since ConcurrentHashMap does not allow null keys, this should throw a NullPointerException.
Execution:
  Arrange: Create a valid LlmFactory implementation.
  Act: Call LlmRegistry.registerLlm(null, factory).
  Assert: Verify that a NullPointerException is thrown.
Validation:
  The assertion confirms that the ConcurrentHashMap's null-key restriction is enforced, preventing null patterns from being registered. This protects against potential NullPointerExceptions during later regex matching operations.

Scenario 8: Register an LLM factory that overrides the default Gemini pattern

Details:
  TestName: registerLlmOverridesDefaultGeminiFactory
  Description: Verify that registerLlm can override the default "gemini-.*" factory that is registered in the static initializer block, replacing it with a custom factory.
Execution:
  Arrange: Create a custom LlmFactory that returns a custom BaseLlm implementation (not a Gemini instance).
  Act: Call LlmRegistry.registerLlm("gemini-.*", customFactory).
  Assert: Call LlmRegistry.getLlm with a new Gemini model name (one not already cached) and verify the returned instance is from the custom factory rather than the default Gemini factory.
Validation:
  The assertion verifies that user-registered factories can override built-in defaults. This is critical for extensibility, allowing users to provide custom implementations for model families that have default factories.

Scenario 9: Register an LLM factory with a pattern that matches all strings

Details:
  TestName: registerLlmWithCatchAllPattern
  Description: Verify that registering a factory with the pattern ".*" (which matches all strings) works correctly and can serve as a fallback factory for any model name.
Execution:
  Arrange: Create a custom LlmFactory implementation. Register it with the pattern ".*".
  Act: Call LlmRegistry.getLlm("any-random-model-name-xyz") with a model name that doesn't match any other specific pattern.
  Assert: Verify that the returned BaseLlm instance was created by the catch-all factory.
Validation:
  The assertion confirms that a universal pattern can be registered to act as a default/fallback factory. This is important for applications that want to ensure all model name lookups succeed regardless of the specific name.

Scenario 10: Register an LLM factory and verify thread-safety of the registration

Details:
  TestName: registerLlmConcurrentRegistration
  Description: Verify that multiple threads can simultaneously call registerLlm with different patterns without causing data corruption or exceptions, leveraging the thread-safe ConcurrentHashMap.
Execution:
  Arrange: Create multiple threads, each with a unique model name pattern and corresponding LlmFactory.
  Act: Start all threads simultaneously, each calling LlmRegistry.registerLlm with its own pattern and factory.
  Assert: After all threads complete, call LlmRegistry.getLlm with model names matching each registered pattern and verify that each returns the correct instance from the expected factory.
Validation:
  The assertion verifies that the ConcurrentHashMap backing the registry provides proper thread safety for concurrent registration operations. This is critical in multi-threaded applications where multiple components might register factories during initialization.

Scenario 11: Register an LLM factory with a pattern containing special regex characters

Details:
  TestName: registerLlmWithSpecialRegexCharactersInPattern
  Description: Verify that registerLlm correctly stores patterns containing special regex characters (such as dots, brackets, etc.) and that these patterns function correctly during matching.
Execution:
  Arrange: Create a custom LlmFactory. Define a pattern with escaped special characters like "model\\.v2\\.\\d+".
  Act: Call LlmRegistry.registerLlm("model\\.v2\\.\\d+", factory).
  Assert: Call LlmRegistry.getLlm("model.v2.5") and verify it returns the expected instance. Call LlmRegistry.getLlm("modelXv2X5") and verify it throws IllegalArgumentException (since dots are escaped and won't match arbitrary characters).
Validation:
  The assertion confirms that special regex characters in patterns are treated literally when escaped, ensuring precise model name matching. This is important for users who need exact pattern matching for model names containing dots or other special characters.

*/

// ********RoostGPT********

package com.google.adk.models;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.lang.reflect.Field;
import java.util.Map;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class LlmRegistryRegisterLlmTest {

  @BeforeEach
  void setUp() throws Exception {
    // Clear the instances and llmFactories maps before each test to ensure isolation
    Field instancesField = LlmRegistry.class.getDeclaredField("instances");
    instancesField.setAccessible(true);
    ((Map<?, ?>) instancesField.get(null)).clear();
    Field factoriesField = LlmRegistry.class.getDeclaredField("llmFactories");
    factoriesField.setAccessible(true);
    ((Map<?, ?>) factoriesField.get(null)).clear();
  }

  @Test
  @Tag("valid")
  void registerLlmWithNewUniquePattern() {
    BaseLlm mockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory factory = modelName -> mockLlm;
    LlmRegistry.registerLlm("custom-model-.*", factory);
    BaseLlm result = LlmRegistry.getLlm("custom-model-test");
    assertNotNull(result);
    assertSame(mockLlm, result);
  }

  @Test
  @Tag("valid")
  void registerLlmOverwritesExistingPatternFactory() {
    BaseLlm mockLlmA = mock(BaseLlm.class);
    BaseLlm mockLlmB = mock(BaseLlm.class);
    LlmRegistry.LlmFactory factoryA = modelName -> mockLlmA;
    LlmRegistry.LlmFactory factoryB = modelName -> mockLlmB;
    LlmRegistry.registerLlm("overwrite-.*", factoryA);
    LlmRegistry.registerLlm("overwrite-.*", factoryB);
    BaseLlm result = LlmRegistry.getLlm("overwrite-test");
    assertNotNull(result);
    assertSame(mockLlmB, result);
  }

  @Test
  @Tag("boundary")
  void registerLlmWithEmptyStringPattern() {
    BaseLlm mockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory factory = modelName -> mockLlm;
    LlmRegistry.registerLlm("", factory);
    BaseLlm result = LlmRegistry.getLlm("");
    assertNotNull(result);
    assertSame(mockLlm, result);
    assertThrows(IllegalArgumentException.class, () -> LlmRegistry.getLlm("non-empty-string"));
  }

  @Test
  @Tag("valid")
  void registerLlmWithComplexRegexPattern() {
    BaseLlm mockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory factory = modelName -> mockLlm;
    LlmRegistry.registerLlm("my-org/[a-z]+-v[0-9]+\\..*", factory);
    BaseLlm result = LlmRegistry.getLlm("my-org/model-v1.0");
    assertNotNull(result);
    assertSame(mockLlm, result);
    assertThrows(IllegalArgumentException.class, () -> LlmRegistry.getLlm("my-org/MODEL-v1.0"));
  }

  @Test
  @Tag("valid")
  void registerMultipleLlmFactoriesWithDifferentPatterns() {
    BaseLlm mockLlmA = mock(BaseLlm.class);
    BaseLlm mockLlmB = mock(BaseLlm.class);
    BaseLlm mockLlmC = mock(BaseLlm.class);
    LlmRegistry.LlmFactory factoryA = modelName -> mockLlmA;
    LlmRegistry.LlmFactory factoryB = modelName -> mockLlmB;
    LlmRegistry.LlmFactory factoryC = modelName -> mockLlmC;
    LlmRegistry.registerLlm("alpha-.*", factoryA);
    LlmRegistry.registerLlm("beta-.*", factoryB);
    LlmRegistry.registerLlm("gamma-.*", factoryC);
    BaseLlm resultAlpha = LlmRegistry.getLlm("alpha-1");
    BaseLlm resultBeta = LlmRegistry.getLlm("beta-2");
    BaseLlm resultGamma = LlmRegistry.getLlm("gamma-3");
    assertSame(mockLlmA, resultAlpha);
    assertSame(mockLlmB, resultBeta);
    assertSame(mockLlmC, resultGamma);
  }

  @Test
  @Tag("invalid")
  void registerLlmWithNullFactory() {
    assertThrows(NullPointerException.class, () -> LlmRegistry.registerLlm("null-test-.*", null));
  }

  @Test
  @Tag("invalid")
  void registerLlmWithNullModelNamePattern() {
    LlmRegistry.LlmFactory factory = modelName -> mock(BaseLlm.class);
    assertThrows(NullPointerException.class, () -> LlmRegistry.registerLlm(null, factory));
  }

  @Test
  @Tag("valid")
  void registerLlmOverridesDefaultGeminiFactory() {
    BaseLlm customLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory customFactory = modelName -> customLlm;
    LlmRegistry.registerLlm("gemini-.*", customFactory);
    BaseLlm result = LlmRegistry.getLlm("gemini-custom-override-test");
    assertNotNull(result);
    assertSame(customLlm, result);
  }

  @Test
  @Tag("valid")
  void registerLlmWithCatchAllPattern() {
    BaseLlm mockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory factory = modelName -> mockLlm;
    LlmRegistry.registerLlm(".*", factory);
    BaseLlm result = LlmRegistry.getLlm("any-random-model-name-xyz");
    assertNotNull(result);
    assertSame(mockLlm, result);
  }

  @Test
  @Tag("integration")
  void registerLlmConcurrentRegistration() throws InterruptedException {
    int threadCount = 10;
    ExecutorService executor = Executors.newFixedThreadPool(threadCount);
    CountDownLatch latch = new CountDownLatch(1);
    CountDownLatch completionLatch = new CountDownLatch(threadCount);
    BaseLlm[] mockLlms = new BaseLlm[threadCount];
    for (int i = 0; i < threadCount; i++) {
      mockLlms[i] = mock(BaseLlm.class);
    }
    for (int i = 0; i < threadCount; i++) {
      final int index = i;
      final BaseLlm llm = mockLlms[i];
      executor.submit(
          () -> {
            try {
              latch.await();
              LlmRegistry.registerLlm("concurrent-" + index + "-.*", modelName -> llm);
            } catch (InterruptedException e) {
              Thread.currentThread().interrupt();
            } finally {
              completionLatch.countDown();
            }
          });
    }
    latch.countDown(); // Start all threads simultaneously
    completionLatch.await(10, TimeUnit.SECONDS);
    executor.shutdown();
    for (int i = 0; i < threadCount; i++) {
      BaseLlm result = LlmRegistry.getLlm("concurrent-" + i + "-test");
      assertNotNull(result);
      assertSame(mockLlms[i], result);
    }
  }

  @Test
  @Tag("valid")
  void registerLlmWithSpecialRegexCharactersInPattern() {
    BaseLlm mockLlm = mock(BaseLlm.class);
    LlmRegistry.LlmFactory factory = modelName -> mockLlm;
    LlmRegistry.registerLlm("model\\.v2\\.\\d+", factory);
    BaseLlm result = LlmRegistry.getLlm("model.v2.5");
    assertNotNull(result);
    assertSame(mockLlm, result);
    assertThrows(IllegalArgumentException.class, () -> LlmRegistry.getLlm("modelXv2X5"));
  }
}
