// ********RoostGPT********
/*
Test generated by RoostGPT for test Test-Java-01 using AI Type Claude AI and AI Model claude-opus-4-6

ROOST_METHOD_HASH=runAsync_85f049b8a2
ROOST_METHOD_SIG_HASH=runAsync_f1104e75e5

Scenario 1: Valid City Returns Weather Data with Expected Keys

Details:
  TestName: validCityReturnsWeatherDataWithExpectedKeys
  Description: Verify that when a valid city name (e.g., "London") is provided in the args map, the method returns a map containing the keys "city", "temperature", and "condition" with appropriate values.
Execution:
  Arrange: Create a Map<String, Object> with the key "city" set to "London". Create a GetWeatherTool instance. Pass null for ToolContext (since it is not used in the method).
  Act: Call runAsync(args, null) and retrieve the resulting Map via blockingGet().
  Assert: Assert that the returned map contains the key "city" with value "London". Assert that the map contains the key "temperature" with a value that is an Integer between 15 and 39 (inclusive). Assert that the map contains the key "condition" with a value that is one of "sunny", "cloudy", "partly cloudy", "rainy", or "overcast".
Validation:
  This assertion verifies that a valid city input produces a well-formed weather response with all expected fields. It ensures the core happy-path behavior of the tool works correctly.

---

Scenario 2: Null City Parameter Returns Error Map

Details:
  TestName: nullCityParameterReturnsErrorMap
  Description: Verify that when the "city" key is present in the args map but its value is null, the method returns a map containing an "error" key with the message "City parameter is required".
Execution:
  Arrange: Create a Map<String, Object> using a HashMap with the key "city" mapped to null. Create a GetWeatherTool instance.
  Act: Call runAsync(args, null) and retrieve the resulting Map via blockingGet().
  Assert: Assert that the returned map contains the key "error" with value "City parameter is required". Assert that the map does not contain keys "temperature" or "condition".
Validation:
  This assertion verifies that null input is properly handled and an informative error message is returned. This is critical for robustness when upstream callers pass incomplete data.

---

Scenario 3: Empty String City Parameter Returns Error Map

Details:
  TestName: emptyCityParameterReturnsErrorMap
  Description: Verify that when the "city" key is mapped to an empty string "", the method returns an error map indicating the city parameter is required.
Execution:
  Arrange: Create a Map<String, Object> with the key "city" set to "". Create a GetWeatherTool instance.
  Act: Call runAsync(args, null) and retrieve the resulting Map via blockingGet().
  Assert: Assert that the returned map contains the key "error" with value "City parameter is required".
Validation:
  This validates that the isNullOrEmpty check correctly catches empty strings. Empty strings should be treated the same as null for this parameter, preventing invalid downstream processing.

---

Scenario 4: Missing City Key in Args Returns Error Map

Details:
  TestName: missingCityKeyInArgsReturnsErrorMap
  Description: Verify that when the args map does not contain the "city" key at all, the method returns an error map because args.get("city") returns null.
Execution:
  Arrange: Create an empty Map<String, Object> (e.g., Map.of()). Create a GetWeatherTool instance.
  Act: Call runAsync(args, null) and retrieve the resulting Map via blockingGet().
  Assert: Assert that the returned map contains the key "error" with value "City parameter is required".
Validation:
  This verifies that the method gracefully handles the case where the expected key is entirely absent from the arguments map, which could happen if the LLM omits the parameter.

---

Scenario 5: Same City Always Returns Deterministic Results

Details:
  TestName: sameCityReturnsDeterministicResults
  Description: Verify that calling runAsync with the same city name multiple times always returns the same temperature and condition, since the simulation is based on a hash function.
Execution:
  Arrange: Create a Map<String, Object> with the key "city" set to "Paris". Create a GetWeatherTool instance.
  Act: Call runAsync(args, null) twice and retrieve both resulting Maps via blockingGet().
  Assert: Assert that the "temperature" values from both calls are equal. Assert that the "condition" values from both calls are equal. Assert that the "city" values from both calls are equal to "Paris".
Validation:
  This confirms the deterministic nature of the simulated weather data. Since the method uses hash-based computation, the same input must always produce the same output, which is important for testability and predictability.

---

Scenario 6: Different Cities May Return Different Results

Details:
  TestName: differentCitiesReturnPotentiallyDifferentResults
  Description: Verify that two different city names (e.g., "Tokyo" and "Sydney") can produce different weather results, demonstrating that the simulation varies by city.
Execution:
  Arrange: Create two separate args maps, one with "city" set to "Tokyo" and another with "city" set to "Sydney". Create a GetWeatherTool instance.
  Act: Call runAsync for each city and retrieve the resulting Maps via blockingGet().
  Assert: Assert that both maps contain valid "city", "temperature", and "condition" keys. Assert that at least one of "temperature" or "condition" differs between the two results (this is highly likely given different hash values).
Validation:
  This validates that the hash-based simulation produces varied outputs for different inputs, ensuring the tool provides city-specific weather data rather than a static response.

---

Scenario 7: Temperature Is Within Expected Range

Details:
  TestName: temperatureIsWithinExpectedRange
  Description: Verify that the temperature returned for any city falls within the range [15, 39] inclusive, as defined by the formula 15 + Math.abs(hash % 25).
Execution:
  Arrange: Create multiple args maps with various city names such as "Berlin", "Mumbai", "Cairo", "New York", "São Paulo". Create a GetWeatherTool instance.
  Act: Call runAsync for each city and retrieve the resulting Maps via blockingGet().
  Assert: For each result, assert that the "temperature" value is >= 15 and <= 39.
Validation:
  This verifies the mathematical bounds of the temperature simulation. The formula guarantees values between 15 and 39, and this test ensures no edge case in hash computation violates these bounds.

---

Scenario 8: Condition Is One of the Predefined Values

Details:
  TestName: conditionIsOneOfPredefinedValues
  Description: Verify that the condition returned for any city is one of the five predefined values: "sunny", "cloudy", "partly cloudy", "rainy", or "overcast".
Execution:
  Arrange: Create multiple args maps with various city names such as "Moscow", "Lagos", "Toronto", "Beijing". Create a GetWeatherTool instance.
  Act: Call runAsync for each city and retrieve the resulting Maps via blockingGet().
  Assert: For each result, assert that the "condition" value is contained in the set {"sunny", "cloudy", "partly cloudy", "rainy", "overcast"}.
Validation:
  This ensures the condition selection logic correctly indexes into the predefined conditions array and never produces an out-of-bounds or unexpected value.

---

Scenario 9: Case Sensitivity - Same City Different Cases Returns Same Results

Details:
  TestName: sameCityDifferentCasesReturnsSameResults
  Description: Verify that the simulated temperature and condition are case-insensitive, since the internal methods use city.toLowerCase(). However, the returned "city" value should preserve the original casing.
Execution:
  Arrange: Create two args maps, one with "city" set to "london" and another with "city" set to "LONDON". Create a GetWeatherTool instance.
  Act: Call runAsync for each and retrieve the resulting Maps via blockingGet().
  Assert: Assert that the "temperature" values are equal for both calls. Assert that the "condition" values are equal for both calls. Assert that the "city" value in the first result is "london" and in the second is "LONDON" (original casing preserved).
Validation:
  This validates that the hash-based simulation is case-insensitive (due to toLowerCase()), ensuring consistent weather data regardless of input casing, while the city name in the response preserves the user's original input.

---

Scenario 10: City Name with Special Characters Returns Valid Result

Details:
  TestName: cityNameWithSpecialCharactersReturnsValidResult
  Description: Verify that a city name containing special characters (e.g., "São Paulo", "Zürich") is handled correctly and returns a valid weather response.
Execution:
  Arrange: Create a Map<String, Object> with the key "city" set to "São Paulo". Create a GetWeatherTool instance.
  Act: Call runAsync(args, null) and retrieve the resulting Map via blockingGet().
  Assert: Assert that the returned map contains "city" with value "São Paulo". Assert that "temperature" is an Integer within [15, 39]. Assert that "condition" is one of the predefined values.
Validation:
  This ensures the method handles Unicode and special characters in city names without errors, which is important for international city names.

---

Scenario 11: City Name with Whitespace Only Returns Error Map

Details:
  TestName: cityNameWithWhitespaceOnlyDoesNotReturnError
  Description: Verify the behavior when the city name is a whitespace-only string (e.g., "   "). Since isNullOrEmpty only checks for null or empty string (""), a whitespace-only string should NOT trigger the error and should return weather data.
Execution:
  Arrange: Create a Map<String, Object> with the key "city" set to "   " (spaces only). Create a GetWeatherTool instance.
  Act: Call runAsync(args, null) and retrieve the resulting Map via blockingGet().
  Assert: Assert that the returned map contains the keys "city", "temperature", and "condition" (not an error), since isNullOrEmpty does not treat whitespace-only strings as empty.
Validation:
  This tests an edge case where the input is technically non-null and non-empty but semantically invalid. It documents the current behavior that whitespace-only strings are treated as valid city names by the method.

---

Scenario 12: Very Long City Name Returns Valid Result

Details:
  TestName: veryLongCityNameReturnsValidResult
  Description: Verify that an extremely long city name string is handled without errors and returns a valid weather response with temperature and condition within expected bounds.
Execution:
  Arrange: Create a Map<String, Object> with the key "city" set to a very long string (e.g., 10,000 characters). Create a GetWeatherTool instance.
  Act: Call runAsync(args, null) and retrieve the resulting Map via blockingGet().
  Assert: Assert that the returned map contains "city", "temperature" (within [15, 39]), and "condition" (one of the predefined values).
Validation:
  This stress-tests the method with an unusually large input to ensure no overflow or unexpected behavior occurs in the hash computation or string processing.

---

Scenario 13: ToolContext Parameter Is Null and Method Still Works

Details:
  TestName: nullToolContextDoesNotAffectExecution
  Description: Verify that passing null as the ToolContext parameter does not cause any exception or affect the result, since the method does not use the ToolContext.
Execution:
  Arrange: Create a Map<String, Object> with the key "city" set to "Rome". Create a GetWeatherTool instance.
  Act: Call runAsync(args, null) and retrieve the resulting Map via blockingGet().
  Assert: Assert that the returned map contains "city" with value "Rome", and valid "temperature" and "condition" values.
Validation:
  This confirms that the ToolContext parameter is not required for the method's operation, which is important for understanding the method's dependencies and for scenarios where ToolContext may not be available.

---

Scenario 14: Return Type Is Single That Emits Exactly One Item

Details:
  TestName: returnTypeSingleEmitsExactlyOneItem
  Description: Verify that the returned Single emits exactly one Map item and completes successfully without errors.
Execution:
  Arrange: Create a Map<String, Object> with the key "city" set to "Dublin". Create a GetWeatherTool instance.
  Act: Call runAsync(args, null) and use RxJava test observer to subscribe.
  Assert: Assert that the test observer received exactly one value, completed without errors, and the emitted value contains the expected keys.
Validation:
  This verifies the reactive contract of the method — that it returns a Single which emits exactly one item and then completes, adhering to the RxJava Single semantics.

---

Scenario 15: Numeric String as City Name Returns Valid Result

Details:
  TestName: numericStringAsCityNameReturnsValidResult
  Description: Verify that a numeric string (e.g., "12345") used as a city name is processed without errors and returns valid weather data.
Execution:
  Arrange: Create a Map<String, Object> with the key "city" set to "12345". Create a GetWeatherTool instance.
  Act: Call runAsync(args, null) and retrieve the resulting Map via blockingGet().
  Assert: Assert that the returned map contains "city" with value "12345", "temperature" within [15, 39], and "condition" as one of the predefined values.
Validation:
  This tests that the method does not perform any validation on the city name format and accepts any non-null, non-empty string, which is consistent with the method's design of simulating weather based on hash values.

*/

// ********RoostGPT********

package com.example;

import static org.junit.jupiter.api.Assertions.*;

import io.reactivex.rxjava3.core.Single;
import io.reactivex.rxjava3.observers.TestObserver;
import java.util.*;
import java.util.Map;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

class GetWeatherToolRunAsyncTest {

  private GetWeatherTool getWeatherTool;

  private static final Set<String> VALID_CONDITIONS =
      Set.of("sunny", "cloudy", "partly cloudy", "rainy", "overcast");

  @BeforeEach
  void setUp() {
    getWeatherTool = new GetWeatherTool();
  }

  @Test
  @Tag("valid")
  void validCityReturnsWeatherDataWithExpectedKeys() {
    Map<String, Object> args = Map.of("city", "London");
    Map<String, Object> result = getWeatherTool.runAsync(args, null).blockingGet();
    assertEquals("London", result.get("city"));
    assertNotNull(result.get("temperature"));
    assertInstanceOf(Integer.class, result.get("temperature"));
    int temperature = (int) result.get("temperature");
    assertTrue(
        temperature >= 15 && temperature <= 39,
        "Temperature should be between 15 and 39, but was " + temperature);
    assertNotNull(result.get("condition"));
    assertTrue(
        VALID_CONDITIONS.contains(result.get("condition")),
        "Condition should be one of predefined values, but was " + result.get("condition"));
  }

  @Test
  @Tag("invalid")
  void nullCityParameterReturnsErrorMap() {
    Map<String, Object> args = new HashMap<>();
    args.put("city", null);
    Map<String, Object> result = getWeatherTool.runAsync(args, null).blockingGet();
    assertEquals("City parameter is required", result.get("error"));
    assertFalse(result.containsKey("temperature"));
    assertFalse(result.containsKey("condition"));
  }

  @Test
  @Tag("invalid")
  void emptyCityParameterReturnsErrorMap() {
    Map<String, Object> args = Map.of("city", "");
    Map<String, Object> result = getWeatherTool.runAsync(args, null).blockingGet();
    assertEquals("City parameter is required", result.get("error"));
  }

  @Test
  @Tag("invalid")
  void missingCityKeyInArgsReturnsErrorMap() {
    Map<String, Object> args = Map.of();
    Map<String, Object> result = getWeatherTool.runAsync(args, null).blockingGet();
    assertEquals("City parameter is required", result.get("error"));
  }

  @Test
  @Tag("valid")
  void sameCityReturnsDeterministicResults() {
    Map<String, Object> args = Map.of("city", "Paris");
    Map<String, Object> result1 = getWeatherTool.runAsync(args, null).blockingGet();
    Map<String, Object> result2 = getWeatherTool.runAsync(args, null).blockingGet();
    assertEquals(result1.get("temperature"), result2.get("temperature"));
    assertEquals(result1.get("condition"), result2.get("condition"));
    assertEquals("Paris", result1.get("city"));
    assertEquals("Paris", result2.get("city"));
  }

  @Test
  @Tag("valid")
  void differentCitiesReturnPotentiallyDifferentResults() {
    Map<String, Object> argsTokyo = Map.of("city", "Tokyo");
    Map<String, Object> argsSydney = Map.of("city", "Sydney");
    Map<String, Object> resultTokyo = getWeatherTool.runAsync(argsTokyo, null).blockingGet();
    Map<String, Object> resultSydney = getWeatherTool.runAsync(argsSydney, null).blockingGet();
    assertEquals("Tokyo", resultTokyo.get("city"));
    assertEquals("Sydney", resultSydney.get("city"));
    assertNotNull(resultTokyo.get("temperature"));
    assertNotNull(resultSydney.get("temperature"));
    assertNotNull(resultTokyo.get("condition"));
    assertNotNull(resultSydney.get("condition"));
    boolean temperatureDiffers =
        !resultTokyo.get("temperature").equals(resultSydney.get("temperature"));
    boolean conditionDiffers = !resultTokyo.get("condition").equals(resultSydney.get("condition"));
    assertTrue(
        temperatureDiffers || conditionDiffers,
        "At least one of temperature or condition should differ between Tokyo and Sydney");
  }

  @ParameterizedTest
  @ValueSource(strings = {"Berlin", "Mumbai", "Cairo", "New York", "São Paulo"})
  @Tag("boundary")
  void temperatureIsWithinExpectedRange(String city) {
    Map<String, Object> args = Map.of("city", city);
    Map<String, Object> result = getWeatherTool.runAsync(args, null).blockingGet();
    int temperature = (int) result.get("temperature");
    assertTrue(
        temperature >= 15 && temperature <= 39,
        "Temperature for " + city + " should be between 15 and 39, but was " + temperature);
  }

  @ParameterizedTest
  @ValueSource(strings = {"Moscow", "Lagos", "Toronto", "Beijing"})
  @Tag("valid")
  void conditionIsOneOfPredefinedValues(String city) {
    Map<String, Object> args = Map.of("city", city);
    Map<String, Object> result = getWeatherTool.runAsync(args, null).blockingGet();
    String condition = (String) result.get("condition");
    assertTrue(
        VALID_CONDITIONS.contains(condition),
        "Condition for " + city + " should be one of predefined values, but was " + condition);
  }

  @Test
  @Tag("valid")
  void sameCityDifferentCasesReturnsSameResults() {
    Map<String, Object> argsLower = Map.of("city", "london");
    Map<String, Object> argsUpper = Map.of("city", "LONDON");
    Map<String, Object> resultLower = getWeatherTool.runAsync(argsLower, null).blockingGet();
    Map<String, Object> resultUpper = getWeatherTool.runAsync(argsUpper, null).blockingGet();
    assertEquals(resultLower.get("temperature"), resultUpper.get("temperature"));
    assertEquals(resultLower.get("condition"), resultUpper.get("condition"));
    assertEquals("london", resultLower.get("city"));
    assertEquals("LONDON", resultUpper.get("city"));
  }

  @Test
  @Tag("valid")
  void cityNameWithSpecialCharactersReturnsValidResult() {
    Map<String, Object> args = Map.of("city", "São Paulo");
    Map<String, Object> result = getWeatherTool.runAsync(args, null).blockingGet();
    assertEquals("São Paulo", result.get("city"));
    int temperature = (int) result.get("temperature");
    assertTrue(
        temperature >= 15 && temperature <= 39,
        "Temperature should be between 15 and 39, but was " + temperature);
    assertTrue(VALID_CONDITIONS.contains(result.get("condition")));
  }

  @Test
  @Tag("boundary")
  void cityNameWithWhitespaceOnlyDoesNotReturnError() {
    Map<String, Object> args = Map.of("city", "   ");
    Map<String, Object> result = getWeatherTool.runAsync(args, null).blockingGet();
    assertTrue(result.containsKey("city"));
    assertTrue(result.containsKey("temperature"));
    assertTrue(result.containsKey("condition"));
    assertFalse(result.containsKey("error"));
  }

  @Test
  @Tag("boundary")
  void veryLongCityNameReturnsValidResult() {
    String longCityName = "A".repeat(10000);
    Map<String, Object> args = Map.of("city", longCityName);
    Map<String, Object> result = getWeatherTool.runAsync(args, null).blockingGet();
    assertEquals(longCityName, result.get("city"));
    int temperature = (int) result.get("temperature");
    assertTrue(
        temperature >= 15 && temperature <= 39,
        "Temperature should be between 15 and 39, but was " + temperature);
    assertTrue(VALID_CONDITIONS.contains(result.get("condition")));
  }

  @Test
  @Tag("valid")
  void nullToolContextDoesNotAffectExecution() {
    Map<String, Object> args = Map.of("city", "Rome");
    Map<String, Object> result = getWeatherTool.runAsync(args, null).blockingGet();
    assertEquals("Rome", result.get("city"));
    assertNotNull(result.get("temperature"));
    int temperature = (int) result.get("temperature");
    assertTrue(temperature >= 15 && temperature <= 39);
    assertTrue(VALID_CONDITIONS.contains(result.get("condition")));
  }

  @Test
  @Tag("valid")
  void returnTypeSingleEmitsExactlyOneItem() {
    Map<String, Object> args = Map.of("city", "Dublin");
    Single<Map<String, Object>> single = getWeatherTool.runAsync(args, null);
    TestObserver<Map<String, Object>> testObserver = single.test();
    testObserver.assertComplete();
    testObserver.assertNoErrors();
    testObserver.assertValueCount(1);
    Map<String, Object> result = testObserver.values().get(0);
    assertTrue(result.containsKey("city"));
    assertTrue(result.containsKey("temperature"));
    assertTrue(result.containsKey("condition"));
  }

  @Test
  @Tag("valid")
  void numericStringAsCityNameReturnsValidResult() {
    Map<String, Object> args = Map.of("city", "12345");
    Map<String, Object> result = getWeatherTool.runAsync(args, null).blockingGet();
    assertEquals("12345", result.get("city"));
    int temperature = (int) result.get("temperature");
    assertTrue(
        temperature >= 15 && temperature <= 39,
        "Temperature should be between 15 and 39, but was " + temperature);
    assertTrue(VALID_CONDITIONS.contains(result.get("condition")));
  }
}
